server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://accounts-service-postgres:5432/account_service
    username: postgres
    password: secret
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html